### ISSUE TITLE
Saving image?

### ISSUE THREAD

**Issue by saac** [mapequation/alluvial-generator#1]
Hello. I like a lot the new Alluvial-Generator

Just a quick question.
Is there any way to save the generated alluvial diagram into an image or pdf format, just like was possible in the old alluvial-generator?

Thanks in advance.

**Comment by antoneri** [comment]
Thanks for the feedback!

This is on the roadmap. We'll try to add this as soon as possible.

**Comment by antoneri** [comment]
I've added experimental support for exporting png and svg. We plan to support exporting pdf as well.

**Comment by saac** [comment]
> I've added experimental support for exporting png and svg. We plan to support exporting pdf as well.

Thanks a lot!
I already tried it and it works pretty well!

Best.
